language: node_js
node_js:
  - 14

addons:
  artifacts:
    debug: true
    paths:
      - ./coverage
    target_paths:
      - /

after_success:
- cat ${TRAVIS_REPO_SLUG}
- cat ${TRAVIS_BUILD_NUMBER}
- cat ${TRAVIS_JOB_NUMBER}
- npm run coverage

